In [3]:
import torch
sample_list = [[1,2,3], [4, 5, 6]]
tensor = torch.tensor(sample_list)
print(tensor)
print(tensor.shape)
print(tensor.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [4]:
a = torch.tensor([[1, 1],
                 [2, 2]])
b = torch.tensor([[1, 1],
                  [2, 2]])
a + b

tensor([[2, 2],
        [4, 4]])

In [5]:
a * b

tensor([[1, 1],
        [4, 4]])

In [6]:
a @ b

tensor([[3, 3],
        [6, 6]])

# Neural networks and layers

In [15]:
import torch.nn as nn
input_tensor = torch.tensor([[.34, 0.45, -0.23]], dtype=torch.float32)
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)
output = linear_layer(input_tensor)
print(output.detach().numpy())
print(f"Weight: {linear_layer.weight}.\nBias: {linear_layer.bias}")

[[ 0.49237207 -0.07752994]]
Weight: Parameter containing:
tensor([[ 0.4694,  0.3554,  0.5128],
        [ 0.2109, -0.1955,  0.5712]], requires_grad=True).
Bias: Parameter containing:
tensor([0.2908, 0.0701], requires_grad=True)


# Hidden layers and parameters

In [16]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(10, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 2)
)

total_parameters = 0
for parameter in model.parameters():
    total_parameters += parameter.numel()

total_parameters

134