# Discovering activation functions

In [3]:
from logging import critical

# sigmoid >> for binary classification
import torch
import torch.nn as nn

input_tensor = torch.tensor([[6]])

sigmoid = nn.Sigmoid()

output = sigmoid(input_tensor)

output

tensor([[0.9975]])

In [6]:
# softmax >> for multi class classification
import torch
import torch.nn as nn

input_tensor = torch.tensor([[4.3, 6.1, 2.3]])

probabilities = nn.Softmax(dim=-1)

output = probabilities(input_tensor)

output

tensor([[0.1392, 0.8420, 0.0188]])

# Running a forward pass

# Using loss functions to assess model predictions

In [7]:
# transforming labels with one-hot encoding
import torch.nn.functional as F

F.one_hot(torch.tensor(0), num_classes=3)

tensor([1, 0, 0])

In [8]:
F.one_hot(torch.tensor(1), num_classes=3)

tensor([0, 1, 0])

In [10]:
F.one_hot(torch.tensor(2), num_classes=3)

tensor([0, 0, 1])

In [12]:
# cross entropy loss
from torch.nn import CrossEntropyLoss

scores = torch.tensor([-5.2, 4.6, 0.8])
one_hot_target = torch.tensor([1, 0, 0])

criterion = CrossEntropyLoss()

criterion(scores.double(), one_hot_target.double())

tensor(9.8222, dtype=torch.float64)

# Using derivatives to update model parameters

In [ ]:
# SGD Stochastic gradient descent
import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.001)

# update parameters
optimizer.step()